name: template_binding
version: 0.14.0+8
author: Polymer.dart Team <web-ui-dev@dartlang.org>
description: >
  Extends the capabilities of the HTML Template Element by enabling it to
  create, manage, and remove instances of content bound to data defined in Dart.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  observable: "^0.14.0"
  observe: "^0.14.0"
  web_components: ">=0.7.0 <0.13.0"
dev_dependencies:
  unittest: ">=0.10.0 <0.12.0"
  browser: ">=0.10.0 <0.11.0"
environment:
  sdk: ">=1.8.0 <2.0.0"
